routes/web.php
<?php
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\AkunController;
use App\Http\Controllers\Admin\KriteriaController;
use App\Http\Controllers\Admin\SubKriteriaController;
use App\Http\Controllers\Admin\HasilController;
use App\Http\Controllers\Admin\AlternatifController;
use App\Http\Controllers\Admin\BobotKriteriaController;
use App\Http\Controllers\Admin\BobotSubKriteriaController;
use App\Http\Controllers\Admin\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['middleware' => 'auth'], function()
{
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('akun', AkunController::class);
    Route::resource('kriteria', KriteriaController::class);
    Route::resource('sub_kriteria', SubKriteriaController::class);
    Route::resource('users', UserController::class);
    Route::get('/hasil', [HasilController::class, 'hasil'])->name('hasil.index');
    Route::get('/data-alternatif', [AlternatifController::class, 'data_alternatif'])->name('data.alternatif');
    Route::get('/hasil/cetak', [HasilController::class, 'cetak'])->name('hasil.cetak');
    Route::resource('alternatif', AlternatifController::class);
    Route::resource('bobot_kriteria', BobotKriteriaController::class);
    Route::resource('bobot_sub_kriteria', BobotSubKriteriaController::class)->parameters(['bobot_sub_kriteria' => 'id']);
});

app/Models/Alternatif.php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Alternatif extends Model
{
    protected $fillable = [
        'nama'
    ];
    protected $table = "alternatif";
    
    public function nilai_alternatif()
    {
        return $this->hasMany('App\Models\NilaiAlternatif', 'id_alternatif', 'id');
    }
}

app/Http/Controllers/Admin/AlternatifController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Alternatif;
use App\Models\NilaiAlternatif;
use App\Models\Kriteria;

class AlternatifController extends Controller
{
    public function index()
    {
        $kriteria = Kriteria::all();
        $data = Alternatif::all();
        return view('alternatif.alternatif')->with('data', $data);
    }
    public function show($id)
    {
        $data = Alternatif::with('nilai_alternatif.sub_kriteria.kriteria')->where('id', $id)->first();
        if($data){
            return view('alternatif.nilai_alternatif')->with('data', $data);
        }
    }
    public function create()
    {
        $kriteria = Kriteria::with('sub_kriteria')->get();
        return view('alternatif.tambah_alternatif')->with('kriteria', $kriteria);
    }
    public function store(Request $request)
    {
        $this->validate($request,[
            'nama' => 'required|unique:alternatif,nama',
         ]);

        $data = new Alternatif;
        $data->nama = request('nama');
        $data->save();
        if(isset($request->nilai)){
            foreach (request('nilai') as $key => $value) {
                $data_nilai = new NilaiAlternatif;
                $data_nilai->id_alternatif = $data->id;
                $data_nilai->id_sub_kriteria = $value;
                $data_nilai->save();
            }
        }
        return redirect()->route('alternatif.index')->with('success',
        'Berhasil menambah data');
    }
    public function edit($id)
    {
        $alternatif = Alternatif::with('nilai_alternatif')->where('id', $id)->first();
        $data = Kriteria::with('sub_kriteria')->get();
        if($data){
            return view('alternatif.edit_alternatif')->with(['data' => $data, 'alternatif' => $alternatif]);
        }
        return redirect()->route('alternatif.index');
    }
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'nama' => 'required'
         ]);

        $data = Alternatif::where('id',$id)->first();
        $data->nama = request('nama');
        $data->save();
        $delete =  NilaiAlternatif::where('id_alternatif', $data->id)->delete();
        foreach (request('nilai') as $key => $value) {
            $data_nilai = new NilaiAlternatif;
            $data_nilai->id_alternatif = $data->id;
            $data_nilai->id_sub_kriteria = $value;
            $data_nilai->save();
        }
        return redirect()->route('alternatif.index')->with('success',
        'Berhasil mengubah data');
    }

    public function destroy($id)
    {
        $data = Alternatif::where('id', $id)->first();
        if($data){
            $data->delete();
        }
        return redirect()->route('alternatif.index')->with('danger',
        'Berhasil menghapus data');
    }

    public function data_alternatif()
    {
        $alternatif = Alternatif::whereHas('nilai_alternatif')->get();
        $kriteria = Kriteria::all(['id','nama']);
        foreach ($alternatif as $key => $value) {
            $data = [];
            foreach ($kriteria as $key2 => $value2) {
                $tmp = NilaiAlternatif::join('alternatif','alternatif.id','=','nilai_alternatif.id_alternatif')
                                    ->join('sub_kriteria','sub_kriteria.id','=','nilai_alternatif.id_sub_kriteria')
                                    ->join('kriteria','kriteria.id','=','sub_kriteria.id_kriteria')
                                    ->where([
                                        'nilai_alternatif.id_alternatif' => $value->id,
                                        'sub_kriteria.id_kriteria' => $value2->id
                                    ])->select([
                                        'sub_kriteria.nama'
                                    ])->first();
                $data[$value2->id] = $tmp->nama;
            }
            $value->data = $data;
        }
        
        $this->data['alternatif'] = $alternatif;
        $this->data['kriteria'] = $kriteria;

        return view('alternatif.data_alternatif',$this->data);
    }
}

resources/views/alternatif/alternatif.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h2 class="m-0 text-dark">ALTERNATIF</h2>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active">Alternatif</li>
            </ol>
        </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <table id="data-admin" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th width="10">NO</th>
                        <th>NAMA</th>
                        <th width="150">NILAI ALTERNATIF</th>
                        <th width="70">AKSI</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data as $sis)
                    <tr>
                        <td class="text-center">{{$loop->iteration}}</td>
                        <td>{{$sis->nama}}</td>
                        <td>
                            <a href="/alternatif/{{$sis->id}}">
                            <span class="badge badge-secondary" data-toggle="tooltip" data-placement="top" title="Ubah">Lihat Nilai Alternatif</span>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="/alternatif/{{$sis->id}}/edit">
                                <button class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Ubah"><i class="fa fa-pencil"></i></button>
                            </a>
                            <form id="delete-siseria-{{$sis->id}}" action="/alternatif/{{$sis->id}}" method="post" style="display: inline;">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Hapus"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</section>
@include ('includes.script')
<script type="text/javascript">
$(document).ready(function(){
    $("#data-admin_length").append('<a  href="{{ route('alternatif.create') }}"> <button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
});
</script>
@endsection

resources/views/alternatif/data_alternatif.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">DATA ALTERNATIF</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">Data Alternatif</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <h3>Tabel Data Alternatif</h3>
            <table id="data-admin" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th width="40">NO</th>
                        <th>ALTERNATIF</th>
                        @foreach ($kriteria as $item)
                            <th>{{ $item->nama }}</th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    @foreach($alternatif as $alt)
                    <tr>
                        <td class="text-center">{{$loop->iteration}}</td>
                        <td>{{ $alt->nama }}</td>
                        @foreach ($alt->data as $data)
                            <td>{{ $data }}</td>
                        @endforeach                        
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <hr>
        <div class="card-body">
            <h3 style="text-align: center;">Detail Data Kriteria</h3>
            <br>
            @foreach ($kriteria as $item)
                <h5>Tabel Keterangan Kriteria <b>{{ $item->nama }}</b></h5>
                <table id="data-admin" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th width="40">NO</th>
                            <th>SUB KRITERIA</th>                            
                            <th>KETERANGAN</th>                            
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($item->sub_kriteria as $sub)
                        <tr>
                            <td class="text-center">{{$loop->iteration}}</td>
                            <td>{{ $sub->nama }}</td>
                            <td>{{ $sub->parameter }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <br>
                <br>
            @endforeach
        </div>
    </div>
</section>
@include ('includes.script')
@endsection

resources/views/alternatif/edit_alternatif.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h2 class="m-0 text-dark">EDIT ALTERNATIF</h2>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active">Edit Alternatif</li>
        </ol>
        </div>
    </div>
    </div>
</div>
<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="/alternatif/{{$alternatif->id}}">
            @csrf
            @method('PATCH')
                <div class="row">
                    <div class="col-md-6">
                        <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputPassword1">Nama</label>
                            <input type="text" class="form-control" value="{{$alternatif->nama}}" name="nama" id="exampleInputPassword1" placeholder="nama">
                        </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            @foreach($data as $krit)
                            <div class="form-group">
                                <label for="exampleInputEmail1">{{$krit->nama}}</label>
                                <select class="form-control" name="nilai[{{$krit->id}}]">
                                @foreach($krit->sub_kriteria as $sub)
                                    <option value="{{$sub->id}}"
                                    @foreach($alternatif->nilai_alternatif as $nil)
                                    @if ($nil->id_sub_kriteria == $sub->id))
                                        selected="selected"
                                    @endif
                                    @endforeach
                                    >{{$sub->nama}} ( {{$sub->parameter}} )</option>
                                @endforeach
                                </select>
                            </div>
                            @endforeach
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary float-right">Ubah</button>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.script')
@endsection

resources/views/alternatif/nilai_alternatif.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0 text-dark">NILAI ALTERNATIF</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active">Nilai Alternatif</li>
        </ol>
        </div>
    </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <td>ID</td>
                                <td>{{$data->id}}</td>
                            </tr>
                            <tr>
                                <td>Nama Alternatif</td>
                                <td>{{$data->nama}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-md-6 col-sm-12">
                    <table id="data-admin" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>NO</th>
                                <th>NAMA KRITERIA</th>
                                <th>NILAI</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data->nilai_alternatif as $nil)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$nil->sub_kriteria->kriteria->nama}}</td>
                                <td>{{$nil->sub_kriteria->nama}}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@include ('includes.script')
<script type="text/javascript">
$(document).ready(function(){
    $("#data-admin_length").append('<a  href="/alternatif/{{$data->id}}/edit"> <button type="button" class="btn btn-outline-primary ml-3">UBAH</button></a>');
});
</script>
@endsection

resources/views/alternatif/tambah_alternatif.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">TAMBAH ALTERNATIF</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">Tambah Alternatif</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="{{ route('alternatif.store') }}">
            @csrf
            <div class="row">
                <div class="col-md-6">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputPassword1">Nama Alternatif</label>
                            <input type="text" class="form-control" name="nama" id="exampleInputPassword1" placeholder="nama">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        @foreach($kriteria as $krit)
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{$krit->nama}}</label>
                            <select class="form-control" name="nilai[{{$krit->id}}]">
                                @foreach($krit->sub_kriteria as $sub)
                                    <option value="{{$sub->id}}">{{$sub->nama}} ( {{$sub->parameter}} )</option>
                                @endforeach
                            </select>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary float-right">Tambah</button>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.script')
@endsection