routes/web.php
<?php
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\AkunController;
use App\Http\Controllers\Admin\KriteriaController;
use App\Http\Controllers\Admin\SubKriteriaController;
use App\Http\Controllers\Admin\HasilController;
use App\Http\Controllers\Admin\AlternatifController;
use App\Http\Controllers\Admin\BobotKriteriaController;
use App\Http\Controllers\Admin\BobotSubKriteriaController;
use App\Http\Controllers\Admin\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['middleware' => 'auth'], function()
{
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('akun', AkunController::class);
    Route::resource('kriteria', KriteriaController::class);
    Route::resource('sub_kriteria', SubKriteriaController::class);
    Route::resource('users', UserController::class);
    Route::get('/hasil', [HasilController::class, 'hasil'])->name('hasil.index');
    Route::get('/data-alternatif', [AlternatifController::class, 'data_alternatif'])->name('data.alternatif');
    Route::get('/hasil/cetak', [HasilController::class, 'cetak'])->name('hasil.cetak');
    Route::resource('alternatif', AlternatifController::class);
    Route::resource('bobot_kriteria', BobotKriteriaController::class);
    Route::resource('bobot_sub_kriteria', BobotSubKriteriaController::class)->parameters(['bobot_sub_kriteria' => 'id']);
});

app/Models/SubKriteria.php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class SubKriteria extends Model
{
    protected $fillable = [
        'id', 'nama'
    ];
    protected $table = "sub_kriteria";
    public $timestamps = false;
    public function kriteria()
    {
        return $this->belongsTo('App\Models\Kriteria', 'id_kriteria', 'id');
    }
}

app/Http/Controllers/Admin/SubKriteriaController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Kriteria;
use App\Models\SubKriteria;

class SubKriteriaController extends Controller
{
    public function show($id)
    {
        $data = Kriteria::with('sub_kriteria')->where('id', $id)->first();
        return view('sub_kriteria.sub_kriteria')->with('data', $data);
    }

    public function create(Request $request)
    {
        $data = Kriteria::where('id', $request->id_kriteria)->first();
        if($data){
            return view('sub_kriteria.tambah_sub_kriteria')->with('data', $data);
        }
        return redirect()->route('kriteria.index');
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'id_kriteria' => 'required|exists:kriteria,id',
            'nama' => 'required',
            'parameter' => 'required'
         ]);

        $data = new SubKriteria;
        $data->id_kriteria = request('id_kriteria');
        $data->nama = request('nama');
        $data->parameter = request('parameter');
        $data->save();
        return redirect('/sub_kriteria/'.request('id_kriteria'))->with('success',
        'Berhasil menambah data');
    }

    public function edit($id)
    {
        $data = SubKriteria::where('id', $id)->first();
        if($data){
            return view('sub_kriteria.edit_sub_kriteria')->with('data', $data);
        }
        return redirect()->route('sub_kriteria.index');
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'nama' => 'required',
            'parameter' => 'required',
         ]);

        $data = SubKriteria::where('id', $id)->first();
        if($data){
            $data->nama = request('nama');
            $data->parameter = request('parameter');
            $data->save();
        }
        return redirect('/sub_kriteria/'.$data->id_kriteria)->with('success',
        'Berhasil mengubah data');
    }

    public function destroy($id)
    {
        $data = SubKriteria::where('id', $id)->first();
        if($data){
            $data->delete();
        }
        return redirect('/sub_kriteria/'.$data->id_kriteria)->with('danger',
        'Berhasil menghapus data');
    }
}

resources/views/sub_kriteria/edit_sub_kriteria.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">EDIT SUB KRITERIA</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="/kriteria">Kriteria</a></li>
                <li class="breadcrumb-item"><a href="/sub_kriteria/{{$data->id_kriteria}}">{{$data->kriteria->nama}}</a></li>
                <li class="breadcrumb-item active">{{$data->nama}}</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="{{ route('sub_kriteria.update', $data->id) }}">
                @csrf
                @method('PATCH')
                <div class="card-body">
                    <div class="form-group">
                        <label>Nama Sub Kriteria</label>
                        <input type="text" class="form-control" name="nama" value="{{$data->nama}}" placeholder="nama">
                    </div>
                    <div class="form-group">
                        <label>Parameter</label>
                        <input type="text" class="form-control" name="parameter" value="{{$data->parameter}}" placeholder="0 - 30 / 31 - 60 / 61 - 100">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Ubah</button>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.script')
@endsection

resources/views/sub_kriteria/sub_kriteria.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">SUB KRITERIA <span class="badge badge-secondary" data-toggle="tooltip" data-placement="top" title="Ubah">{{$data->nama}}</span></h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="/kriteria">Sub Kriteria</a></li>
                <li class="breadcrumb-item active">{{$data->nama}}</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <table id="data-admin" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th width="40">NO</th>
                        <th>NAMA</th>
                        <th>PARAMETER</th>
                        <th width="80">AKSI</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data->sub_kriteria as $krit)
                    <tr>
                        <td class="text-center">{{$loop->iteration}}</td>
                        <td>{{$krit->nama}}</td>
                        <td>{{$krit->parameter}}</td>
                        <td>
                            <a href="/sub_kriteria/{{$krit->id}}/edit">
                            <span class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Ubah"><i class="fa fa-pencil"></i></span>
                            </a>
                            <form id='delete-kriteria{{$krit->id}}' action="/sub_kriteria/{{$krit->id}}" method="post" style="display: inline;">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Hapus"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</section>
@include ('includes.script')
<script type="text/javascript">
$(document).ready(function(){
    $("#data-admin_length").append('<a  href="{{ route('sub_kriteria.create', ['id_kriteria' => $data->id]) }}"> <button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
});
</script>
@endsection

resources/views/sub_kriteria/tambah_sub_kriteria.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">TAMBAH SUB KRITERIA <span class="badge badge-secondary" data-toggle="tooltip" data-placement="top" title="Ubah">{{$data->nama}}</span></h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="/kriteria">Kriteria</a></li>
                <li class="breadcrumb-item active">{{$data->nama}}</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="{{ route('sub_kriteria.store') }}">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Kriteria</label>
                        <input type="text" class="form-control" value="{{$data->nama}}" disabled id="exampleInputEmail1" placeholder="id">
                        <input type="hidden" class="form-control" value="{{$data->id}}" name="id_kriteria" id="exampleInputEmail1" placeholder="id">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nama Sub Kriteria</label>
                        <input type="text" class="form-control" name="nama" id="exampleInputPassword1" placeholder="nama">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Parameter</label>
                        <input type="text" class="form-control" name="parameter" id="exampleInputPassword1" placeholder="masukkan keterangan">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Tambah</button>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.script')
@endsection