routes/web.php
<?php
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\AkunController;
use App\Http\Controllers\Admin\KriteriaController;
use App\Http\Controllers\Admin\SubKriteriaController;
use App\Http\Controllers\Admin\HasilController;
use App\Http\Controllers\Admin\AlternatifController;
use App\Http\Controllers\Admin\BobotKriteriaController;
use App\Http\Controllers\Admin\BobotSubKriteriaController;
use App\Http\Controllers\Admin\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['middleware' => 'auth'], function()
{
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('akun', AkunController::class);
    Route::resource('kriteria', KriteriaController::class);
    Route::resource('sub_kriteria', SubKriteriaController::class);
    Route::resource('users', UserController::class);
    Route::get('/hasil', [HasilController::class, 'hasil'])->name('hasil.index');
    Route::get('/data-alternatif', [AlternatifController::class, 'data_alternatif'])->name('data.alternatif');
    Route::get('/hasil/cetak', [HasilController::class, 'cetak'])->name('hasil.cetak');
    Route::resource('alternatif', AlternatifController::class);
    Route::resource('bobot_kriteria', BobotKriteriaController::class);
    Route::resource('bobot_sub_kriteria', BobotSubKriteriaController::class)->parameters(['bobot_sub_kriteria' => 'id']);
});

resources/views/includes/flash.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success" role="alert">{{$message }}</div>
@endif

@if ($message = Session::get('danger'))
<div class="alert alert-danger">{{$message }}</div>
@endif

@if ($message = Session::get('warning'))
<div class="alert alert-warning">{{$message }}</div>
@endif

@if ($message = Session::get('info'))
<div class="alert alert-info">{{$message }}</div>
@endif

@if ($errors->any())
<div class="alert alert-danger">
    @foreach ($errors->all() as $error)
        <ul>
            <li>{{ $error }}</li>
        </ul>
    @endforeach
</div>
@endif

resources/views/includes/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; SPK PEMILIHAN JURUSAN 2021</span>
        </div>
    </div>
</footer>

resources/views/includes/navbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    {{ config('app.name') }}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ auth()->user()->name }}</span>
                <img class="img-profile rounded-circle"
                    src="img/undraw_profile.svg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{{ route('akun.index') }}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Akun
                </a>
                <div class="dropdown-divider"></div>
                <form id="logout-form" action="{{ route('logout') }}" method="POST">
                    @csrf
                    <button class="dropdown-item" href="#">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Logout
                    </button>
                </form>
            </div>
        </li>

    </ul>

</nav>

resources/views/includes/script.blade.php
<!-- jQuery -->
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('dist/js/adminlte.js') }}"></script>
<script>
  $(function () {
    $("#data-admin").DataTable();
    $("#data-admin-1").DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "language": {
          "sEmptyTable":   "Tidak ada data yang tersedia pada tabel ini",
    "sProcessing":   "Sedang memproses...",
    "sLengthMenu":   "Tampilkan _MENU_ entri",
    "sZeroRecords":  "Tidak ditemukan data yang sesuai",
    "sInfo":         "Menampilkan _START_ sampai _END_ dari _TOTAL_ entri",
    "sInfoEmpty":    "Menampilkan 0 sampai 0 dari 0 entri",
    "sInfoFiltered": "(disaring dari _MAX_ entri keseluruhan)",
    "sInfoPostFix":  "",
    "sSearch":       "Cari:",
    "sUrl":          "",
    "oPaginate": {
        "sFirst":    "Pertama",
        "sPrevious": "Sebelumnya",
        "sNext":     "Selanjutnya",
        "sLast":     "Terakhir"
    }
        }
    });
  });
</script>

resources/views/includes/sidebar.blade.php
<ul class="navbar-nav bg-gradient-info sidebar sidebar-dark accordion" id="accordionSidebar">

    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SPK PEMILIHAN <sup>JURUSAN</sup></div>
    </a>

    <hr class="sidebar-divider my-0">

    <li class="nav-item {{ Request::is('/') ? 'active' : '' }}">
        <a class="nav-link" href="/">
            <i class="fa fa-tachometer"></i>
            <span>Dashboard</span></a>
    </li>

    <hr class="sidebar-divider">

    @if(auth()->user()->role == 'admin')
    <div class="sidebar-heading">
        Master Data
    </div>

    <li class="nav-item {{ Request::is('users') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('users.index') }}">
            <i class="fa fa-users"></i>
            <span>USERS</span>
        </a>
    </li>
    <li class="nav-item {{ Request::is('kriteria') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('kriteria.index') }}">
            <i class="fa fa-list"></i>
            <span>KRITERIA</span>
        </a>
    </li>
    <li class="nav-item {{ Request::is('alternatif') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('alternatif.index') }}">
            <i class="fa fa-list"></i>
            <span>ALTERNATIF</span>
        </a>
    </li>

    <hr class="sidebar-divider">

    <div class="sidebar-heading">
        Analisis
    </div>

    <li class="nav-item {{ Request::is('bobot_kriteria') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('bobot_kriteria.index') }}">
            <i class="fa fa-balance-scale"></i>
            <span>BOBOT KRITERIA</span>
        </a>
    </li>

    <li class="nav-item {{ Request::is('bobot_sub_kriteria') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('bobot_sub_kriteria.index') }}">
            <i class="fa fa-balance-scale"></i>
            <span>BOBOT SUB KRITERIA</span>
        </a>
    </li>

    <hr class="sidebar-divider">

    <div class="sidebar-heading">
        Hasil
    </div>

    <li class="nav-item {{ Request::is('hasil') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('hasil.index') }}">
            <i class="fa fa-check"></i>
            <span>HASIL</span>
        </a>
    </li>
    @else
    {{-- <li class="nav-item {{ Request::is('data.alternatif') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('data.alternatif') }}">
            <i class="fa fa-list"></i>
            <span>DATA ALTERNATIF</span>
        </a>
    </li> --}}
    <li class="nav-item {{ Request::is('bobot_kriteria') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('bobot_kriteria.index') }}">
            <i class="fa fa-balance-scale"></i>
            <span>BOBOT KRITERIA</span>
        </a>
    </li>
    <li class="nav-item {{ Request::is('hasil') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('hasil.index') }}">
            <i class="fa fa-check"></i>
            <span>HASIL</span>
        </a>
    </li>
    @endif

    <hr class="sidebar-divider d-none d-md-block">

    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>