routes/web.php
<?php
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\AkunController;
use App\Http\Controllers\Admin\KriteriaController;
use App\Http\Controllers\Admin\SubKriteriaController;
use App\Http\Controllers\Admin\HasilController;
use App\Http\Controllers\Admin\AlternatifController;
use App\Http\Controllers\Admin\BobotKriteriaController;
use App\Http\Controllers\Admin\BobotSubKriteriaController;
use App\Http\Controllers\Admin\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['middleware' => 'auth'], function()
{
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('akun', AkunController::class);
    Route::resource('kriteria', KriteriaController::class);
    Route::resource('sub_kriteria', SubKriteriaController::class);
    Route::resource('users', UserController::class);
    Route::get('/hasil', [HasilController::class, 'hasil'])->name('hasil.index');
    Route::get('/data-alternatif', [AlternatifController::class, 'data_alternatif'])->name('data.alternatif');
    Route::get('/hasil/cetak', [HasilController::class, 'cetak'])->name('hasil.cetak');
    Route::resource('alternatif', AlternatifController::class);
    Route::resource('bobot_kriteria', BobotKriteriaController::class);
    Route::resource('bobot_sub_kriteria', BobotSubKriteriaController::class)->parameters(['bobot_sub_kriteria' => 'id']);
});

app/Models/Kriteria.php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Kriteria extends Model
{
    protected $fillable = [
        'id', 'nama'
    ];
    protected $table = "kriteria";
    public function sub_kriteria()
    {
        return $this->hasMany('App\Models\SubKriteria', 'id_kriteria', 'id');
    }
    public function bobot_kriteria()
    {
        return $this->hasMany('App\Models\BobotKriteria', 'id_kriteria_1', 'id');
    }
}

app/Http/Controllers/Admin/KriteriaController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Kriteria;

class KriteriaController extends Controller
{
    public function index()
    {
        $data = Kriteria::all();
        return view('kriteria.kriteria')->with('data', $data);
    }

    public function create()
    {
        return view('kriteria.tambah_kriteria');
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'nama' => 'required'
         ]);

        $data = new Kriteria;
        $data->nama = request('nama');
        $data->save();
        return redirect()->route('kriteria.index')->with('success',
        'Berhasil menambah data');
    }

    public function edit($id)
    {
        $data = Kriteria::where('id', $id)->first();
        if($data){
            return view('kriteria.edit_kriteria')->with('data', $data);
        }
        return redirect()->route('kriteria.index');
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'nama' => 'required'
         ]);

        $data = Kriteria::where('id', $id)->first();
        if($data){
            $data->nama = request('nama');
            $data->save();
        }
        return redirect()->route('kriteria.index')->with('success',
        'Berhasil mengubah data');
    }

    public function destroy($id)
    {
        $data = Kriteria::where('id', $id)->first();
        if($data){
            $data->delete();
        }
        return redirect()->route('kriteria.index')->with('danger',
        'Berhasil menghapus data');
    }
}

resources/views/kriteria/edit_kriteria.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">EDIT KRITERIA</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">KRITERIA / EDIT</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="{{ route('kriteria.update', $data->id) }}">
                @csrf
                @method('PATCH')
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nama Kriteria</label>
                        <input type="text" class="form-control" name="nama" value="{{$data->nama}}" id="exampleInputPassword1" placeholder="nama">
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Ubah</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.script')
@endsection

resources/views/kriteria/kriteria.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">KRITERIA</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">Kriteria</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <table id="data-admin" class="table table-bordered table-striped">
                <thead>
                    <tr>
                    <th width="40">NO</th>
                    <th>NAMA</th>
                    <th width="240">SUB KRITERIA</th>
                    <th width="80">AKSI</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data as $krit)
                    <tr>
                        <td class="text-center">{{$loop->iteration}}</td>
                        <td>{{$krit->nama}}</td>
                        <td>
                            <a href="/sub_kriteria/{{$krit->id}}">
                            <span class="badge badge-secondary" data-toggle="tooltip" data-placement="top" title="Ubah">Lihat Sub Kriteria</span>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="/kriteria/{{$krit->id}}/edit">
                            <button class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Ubah"><i class="fa fa-pencil"></i></button>
                            </a>
                            <form id="delete-kriteria-{{$krit->id}}" action="/kriteria/{{$krit->id}}" method="post" style="display: inline;">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Hapus"><i class="fa fa-trash"></i></button>
                            </form>

                        </td>

                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</section>
@include ('includes.script')
<script type="text/javascript">
$(document).ready(function(){
    $("#data-admin_length").append('<a  href="{{ route('kriteria.create') }}"> <button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
});
</script>
@endsection

resources/views/kriteria/tambah_kriteria.blade.php
@extends('layouts.app')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">Tambah Kriteria</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">Kriteria</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="{{ route('kriteria.store') }}">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nama Kriteria</label>
                        <input type="text" class="form-control" name="nama" id="exampleInputPassword1" placeholder="nama">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.script')
@endsection